# This is a docker compose file for defining and running
# multi-container environments. It simplifies the control
# of your application stack into a single configuration
# file. The following commands are useful:
#
#   docker compose up          - "runs" the entire system
#   docker compose up --build  - force a build and "runs" system
#   docker compose up -d       - "runs" system in detacted mode
#   docker compose down        - "closes" the entire system and deletes everything
#   docker compose stop        - stop running containers without removing them
#   docker compose start       - start previously stopped containers
#
version: '3.9'
name: microservices

services:
  registry:
    build:
      context: ./registry
    container_name: registry
    networks:
      - palnet

  react:
    build:
      context: ./react
    ports:
      - "5173:5173"
    volumes:
      - ./react:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: react
    depends_on:
      - registry
    networks:
      - palnet

  database:
    build:
      context: ./database
    container_name: database
    depends_on:
      - registry
    networks:
      - palnet

  # backend:
  #   build:
  #     context: ./backend
  #   container_name: backend
  #   depends_on:
  #     - registry
  #   networks:
  #     - palnet

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    depends_on:
      - react
      - database
      # - backend
    networks:
      - palnet
    ports:
      - "3000:3000"

networks:
  palnet:
    driver: bridge